/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessBlockedRouteImport } from './routes/access-blocked'
import { Route as FirstTimeAccessRouteImport } from './routes/first-time-access'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as ApiHelloRouteImport } from './routes/api.hello'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessBlockedRoute = AccessBlockedRouteImport.update({
  id: '/access-blocked',
  path: '/access-blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstTimeAccessRoute = FirstTimeAccessRouteImport.update({
  id: '/first-time-access',
  path: '/first-time-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-blocked': typeof AccessBlockedRoute
  '/first-time-access': typeof FirstTimeAccessRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-blocked': typeof AccessBlockedRoute
  '/first-time-access': typeof FirstTimeAccessRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-blocked': typeof AccessBlockedRoute
  '/first-time-access': typeof FirstTimeAccessRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-blocked'
    | '/first-time-access'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/admin/members'
    | '/admin/organizations'
    | '/api/hello'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-blocked'
    | '/first-time-access'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/admin/members'
    | '/admin/organizations'
    | '/api/hello'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/access-blocked'
    | '/first-time-access'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/admin/members'
    | '/admin/organizations'
    | '/api/hello'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessBlockedRoute: typeof AccessBlockedRoute
  FirstTimeAccessRoute: typeof FirstTimeAccessRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  ApiHelloRoute: typeof ApiHelloRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-blocked': {
      id: '/access-blocked'
      path: '/access-blocked'
      fullPath: '/access-blocked'
      preLoaderRoute: typeof AccessBlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-time-access': {
      id: '/first-time-access'
      path: '/first-time-access'
      fullPath: '/first-time-access'
      preLoaderRoute: typeof FirstTimeAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessBlockedRoute: AccessBlockedRoute,
  FirstTimeAccessRoute: FirstTimeAccessRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  ApiHelloRoute: ApiHelloRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
